version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  # image project
  taskrise:
    container_name: taskrise
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # nginx
  nginx:
    image: nginx:alpine
    container_name: taskrise-serve
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  banco-taskrise:
    container_name: banco-taskrise
    image: postgres:15.1
    networks:
      - app-network
    environment:
      PGUSER: laravel
      POSTGRES_DB: taskrise
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 112233
      PGDATA: /data/taskrise
    volumes:
      - ./banco-taskrise:/data/taskrise
    ports:
      - "2002:5432"
